### ISSUE TITLE
Issue with zsvdc_

### ISSUE THREAD

**Issue by astrozot** [lvandeve/jmat#10]
The following code throws an exception:

> M=Matrix([[1,0,1], [0,1,1], [0,0,0]])
> b=Matrix([1,1,0])
> Jmat.solve(M, b)
TypeError: undefined is not a function
    at Function.Jmat.Matrix.zsvdc_ (repl:242:25)
    at Function.Jmat.Matrix.svd (repl:26:13)
    at Function.Jmat.Matrix.pseudoinverse_ (repl:3:23)
    at Function.Jmat.Matrix.pseudoinverse (repl:11:20)
    at Function.Jmat.Matrix.solve (repl:3:22)
    at Function.Jmat.solve (repl:1:50)
    at repl:1:6
    at REPLServer.defaultEval (repl.js:132:27)
    at bound (domain.js:254:14)
    at REPLServer.runBound [as eval] (domain.js:267:12)

**Comment by astrozot** [comment]
Just to elaborate: the problem is at the line 8074 with the quantity e[l - 1].abs(): after a few iterations e is not an array of objects anymore, but has a simple float as first element.  

A possible origin of this problem is at line 8119, where 

e[k - 2] = cs * e[k - 2];

This should probably be something like

e[k - 2] = e[k - 2].mul(cs);

This solves part of the problem: in this case I do not get the exception anymore (which is good...), but the solution is full of NaNs (which is not...).

**Comment by lvandeve** [comment]
Thanks for finding this bug. And also for finding that unconverted "*" in all that code mess! This was converted from fortran to JS, guess I didn't end up in this code path in my testing :(

The bug is now fixed, even the nans, with e[k - 2] = e[k - 2].mulr(cs): mulr with r for "real number argument".
